model: yolov8m-seg.pt
data: data/floodnet/processed/waterlogging.yaml
imgsz: 1024
epochs: 500
batch: 4
device: 0
workers: 2
cache: false
amp: true
cos_lr: true
close_mosaic: 30
patience: 100
optimizer: AdamW
lr0: 0.0003
momentum: 0.9
weight_decay: 0.0005
hsv_h: 0.015
hsv_s: 0.40
hsv_v: 0.40
degrees: 15
translate: 0.10
scale: 0.50
fliplr: 0.50
flipud: 0.50
mosaic: 0.80
mixup: 0.05
project: runs/segment
name: floodnet_yolov8m_1024_b4
exist_ok: false
