model: runs/segment/runs/segment/combined_sen2gf3_gf_yolov8m_640_b16_e300_from_sen2gf3_last-3/weights/best.pt
data: data/gf_floodnet/processed/waterlogging.yaml
imgsz: 640
epochs: 200
batch: 16
device: 0
workers: 2
cache: false
amp: true
cos_lr: true
close_mosaic: 20
patience: 50
optimizer: AdamW
lr0: 0.0001
momentum: 0.9
weight_decay: 0.0005
hsv_h: 0.01
hsv_s: 0.30
hsv_v: 0.30
degrees: 8
translate: 0.10
scale: 0.40
fliplr: 0.50
flipud: 0.50
mosaic: 0.60
mixup: 0.03
project: runs/segment
name: gf_floodnet_yolov8m_640_b16_from_combined_best
exist_ok: false
