model: runs/segment/runs/segment/sen2gf3_yolov8m_640/weights/last.pt
data: data/combined_sen2gf3_gf/processed/waterlogging.yaml
imgsz: 640
epochs: 500
batch: 16
device: 0
workers: 2
cache: false
amp: true
cos_lr: true
close_mosaic: 10
patience: 30
optimizer: AdamW
lr0: 0.0003
momentum: 0.9
weight_decay: 0.0005
project: runs/segment
name: combined_sen2gf3_gf_yolov8m_640_b16_e300_from_sen2gf3_last
exist_ok: false
